### ISSUE TITLE
Warning on runserver, "null has no effect on ManyToManyField"

### ISSUE THREAD

**Issue by diwant** [dokterbob/django-portfolio#5]
Everything is working well, thank you for this plugin.  When I run `python manage.py runserver`, I am shown a warning that says

```
portfolio.Artwork.categories: (fields.W340) null has no effect on ManyToManyField
```

I am using Django 1.8.5

**Comment by dokterbob** [comment]
Seems easy to fix - just remove default=None. Looking forward to your pull request! 

(Don’t worry if you screw up, I’ll give you some tips along the way if you need them.)

**Comment by dokterbob** [comment]
Thanks!
