### ISSUE TITLE
portfolio.Price.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract

### ISSUE THREAD

**Issue by ravinkaur** [dokterbob/django-portfolio#9]
SystemCheckError, when i run the command **_python ./manage.py migrate_**

Errors:

SystemCheckError: System check identified some issues:

ERRORS:

**portfolio.Price.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract.
portfolio.Transaction.currency: (fields.E300) Field defines a relation with model 'Currency', which is either not installed, or is abstract.**

I'm quite new to Django. Can you help me how to solve this issue.

Any solutions?

Thank you,
Ravin

**Comment by dokterbob** [comment]
Hey,

Seems you have been modifying the model or something as there is no currency or transaction in portfolio. Please fix your own problems before making them mine. ;)

So: try to get the package to work on a pristine setup before reporting issues.

Please close this issue.

Thanks!
Mathijs
